"""Build the dependency-free script from the maintained package sources."""
import pathlib
import pprint

ROOT = pathlib.Path(__file__).resolve().parents[1]
ORDER = ['__init__', 'model', 'files', 'scan', 'capture_time', 'metadata', 'config', 'api', 'manifest', 'hashcache', 'runner', 'cli']
sources = [(name, (ROOT / 'src/camera_importer' / (name + '.py')).read_text()) for name in ORDER]
header = '''#!/usr/bin/env python3
"""Standalone camera importer. Generated by tools/build_standalone.py.

Requires Python 3.8+, Immich CLI and ExifTool. No pip packages required.
Source modules are embedded as plain Python text and loaded in memory.
"""
import sys
import types

if sys.version_info < (3, 8):
    sys.exit("camera-import requires Python 3.8 or newer")

SOURCES = '''
footer = '''

def main():
    for short_name, source in SOURCES:
        name = "camera_importer" if short_name == "__init__" else "camera_importer." + short_name
        module = types.ModuleType(name)
        module.__file__ = __file__ + "/" + short_name + ".py"
        module.__package__ = "camera_importer"
        if short_name == "__init__":
            module.__path__ = []
        sys.modules[name] = module
        if short_name != "__init__":
            setattr(sys.modules["camera_importer"], short_name, module)
        exec(compile(source, module.__file__, "exec"), module.__dict__)
    return sys.modules["camera_importer.cli"].main()


if __name__ == "__main__":
    sys.exit(main())
'''
(ROOT / 'camera-import.py').write_text(header + pprint.pformat(sources, width=100, sort_dicts=False) + footer)
